# Generated by Django 2.2.7 on 2019-11-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='question_text',
        ),
    ]
