# Generated by Django 2.2.7 on 2019-12-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_postphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postphoto',
            old_name='package',
            new_name='post',
        ),
    ]
